server:
  port: 18082
spring:
  application:
    name: user-consumer
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka # EurekaServer的地址
user-provider:
  ribbon:
    #轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 1000 # 连接超时时间 没有连接上
    ReadTimeout: 2000 # 数据读取超时时间 连接上了，连上之后开始计时，但读取数据需要花费很长时间
    MaxAutoRetries: 1 # 最大重试次数(第一个服务)在第一次连接超时之后，在重新连接一次
#    MaxAutoRetriesNextServer: 0 # 最大重试下一个服务次数(集群的情况才会用到)
#    OkToRetryOnAllOperations: false # 是否所有操作都进行重试
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:    text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true
logging:
  level:
    com.atguigu: debug